service: cloud-computations-serverless

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-central-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action: "dynamodb:*"
          Resource: !Sub "arn:aws:dynamodb:::${FilesTable}/*"
        - Effect: Allow
          Action: "s3:*"
          Resource: !Sub "arn:aws:s3:::${UserUploadBucket}/*"

package:
  # Create separate zip for each Lambda function
  individually: true
  patterns:
    # Exclude everything (each Lambda will specify which directory should be included)
    # To exclude use '!' prefix
    - '!**/**'
    - 'build/common/**'
    - 'node_modules/**'

functions:
  create:
    handler: build/create.lambdaHandler
    package:
      include: 'build/create.js'
    events:
      - http:
          path: todos
          method: post
          cors: true
          authorizer:
              name: PrivateAuthorizer
              type: COGNITO_USER_POOLS
              arn:
                Fn::GetAtt:
                  - UserPool
                  - Arn
              claims:
                - email

  list:
    handler: build/list.lambdaHandler
    package:
      include: 'build/list.js'
    events:
      - http:
          path: todos
          method: get
          cors: true
        
  get:
    handler: build/get.lambdaHandler
    package:
      include: 'build/get.js'
    events:
      - http:
          path: build/{id}
          method: get
          cors: true
        
  update:
    handler: build/update.lambdaHandler
    package:
      include: 'build/update.js'
    events:
      - http:
          path: build/{id}
          method: put
          cors: true        

resources:
  Resources:
    FilesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Files
        AttributeDefinitions:
          - AttributeName: user_sub
            AttributeType: S
          - AttributeName: file_id
            AttributeType: S
        KeySchema:
          - AttributeName: user_sub
            KeyType: HASH
          - AttributeName: file_id
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    UserUploadBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: tim18-cloud-computing-user-upload
    UserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: MyUserPool
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireLowercase: true
            RequireNumbers: true
            RequireSymbols: true
            RequireUppercase: true
        Schema:
          - AttributeDataType: String
            DeveloperOnlyAttribute: false
            Mutable: true
            Name: email
            Required: true
            StringAttributeConstraints:
              MinLength: "3"
              MaxLength: "255"
          - AttributeDataType: String
            DeveloperOnlyAttribute: false
            Mutable: true
            Name: phone_number
            Required: true
            StringAttributeConstraints:
              MinLength: "3"
              MaxLength: "255"
        AutoVerifiedAttributes:
          - email
        UsernameAttributes:
          - email
        EmailVerificationMessage: "Your verification code is {####}."
        EmailVerificationSubject: "Verify your email address"

